0xsoniclabs/tosca

rust/src/interpreter.rs
rust/src/utils/gas.rs

Unlike for gas_left, it seems to be expected that gas_refund DOES overflow.
This PR removed the overflow check which makes the regression tests pass.

evmrs: let gas_refund overflow to pass regressions

---

rust/src/types/code_analysis.rs

The code analysis size (in the number of entries) was taken from evmzero. However, some features blow up the size of the internal representation of each entry. This leads to too much memory consumption. This PR therefore decreases the number of entries in those cases to keep the cache size in bytes roughly the same.

evmrs: adjust code cache size depending on enabled features

---

rust/src/interpreter.rs
rust/src/types/stack.rs

This PR adds the method `pop_with_guard` to Stack, which works similar to the normal `pop` method, but additionally returns a PushGuard which holds a mutable reference to the location in the stack where the result can be pushed to. Because we popped values first, pushing a single value will never overflow the stack. 
Unfortunately, when first poping values and then pushing a single value, the compiler does not figure this out and adds the check for the (evm)stack overflow. With this optimization, this check is now gone.
While this optimization does decrease performance on old hardware (probably because of code layout reasons), it does improve performance on new hardware, which is what matters at the end of the day.
```
goos: linux
goarch: amd64
pkg: …
```

evmrs: use push guard to avoid stack overflow checks

---

rust/src/types/code_reader.rs

This PR adds unsafe compiler hints to remove bound checks.
The idea is that when feature fn-ptr-conversion-expanded-dispatch is enabled, the analysis item holds both the function pointer for the corresponding opcode impl and a u256 used as push data.
The function pointer is retrieved first in order to call the function.
In case the function is Interpreter::push, it calls get_push_data to get the data to push onto the stack.
Because we already retrieved the function pointer, and the pc was not modified in between, it is not necessary to check the bounds again when accessing the same analysis item again to get the push data.

no bounds checks in get_push_data

---

rust/Cargo.toml
rust/src/interpreter.rs
rust/src/types/stack.rs

- remove jumptable-dispatch from performance feature, because fn-ptr-conversion-expanded-dispatch has higher precedence anyway
- specify precedence of function dispatch features in Cargo.toml
- remove unnecessary lint suppression
- fix typos and outdated variable names

evmrs: cleanup

---

go.mod
go.sum
go/ct/gen/state.go
regression_inputs/no_code_#5.json

`returnData` is write only, therefore it should not be set in the CT state generation. RETURNDATASIZE and RETURNDATACOPY opcodes are reading from `lastCallReturnData`.

CT: No code is treated as STOP

---

.testcoverage.yml
go.mod
go.sum
go/integration_test/processor/gas_billing_test.go
go/integration_test/processor/processor_test.go
go/processor/geth/processor.go
go/processor/geth/processor_test.go
go/processor/geth/state_contract.go

For the release of the Sonic network the processor implementation has been updated to the one from ethereum with only minor changes. To be able to test Floria against this new implementation, it is added as a processor option to tosca.
Tests to check this integration:

Geth processor reference implementation

---

go/geth_adapter/adapter_test.go
go/geth_adapter/state_db.go
go/geth_adapter/state_db_test.go
go/interpreter/geth/ct.go
go/interpreter/geth/geth.go
go/processor/geth/processor.go
go/processor/opera/processor.go
go/tosca_adapter/state_db.go

The state db used for the geth-interpreter and geth-processor are identical, this PR merges them into a single file.

Combine geth to tosca state dbs

---

go/processor/geth/processor.go
go/tosca/processor.go

This PR extends the `tosca.Transaction` with the `blobHashes` and `blobBaseFeeCap`, required to enable blob transaction support. These fields are converted and forwarded in the geth processor.

Geth processor: Add blob support

---

go/ct/utils/adapter.go
go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go
go/geth_adapter/state_db.go
go/integration_test/interpreter/test_evm.go
go/integration_test/processor/scenario.go
go/tosca/interpreter.go
go/tosca/interpreter_mock.go
go/tosca/world_state.go
go/tosca/world_state_mock.go

The transaction context interface has been extended by two functions, `CreateAccount` and `HasEmptyStateRoot`. Both are required by the processor to manage account life times in create and selfdestruct instructions.

Extend transaction context

---

.gitignore
go/ct/evm_fuzz_test.go

During migration of old organization issues [issue 549](https://github.com/Fantom-foundation/Tosca/issues/549) was found.
The stated error cannot be reproduced anymore, and evmzero fuzzer (go-driven)  can be enabled.  This means that the fuzzer test will be treated as an unit test for each corpus (generated and stored)  during unit testing rounds.
Additionally it allows to fuzz the C++ vm.
- `go test -fuzz=FuzzEvmzero ./go/ct`
- `go test -fuzz=FuzzDifferentialEvmzeroVsGeth ./go/ct`

EVMZERO: Enable fuzzing tests

---

cpp/cmake/tosca_coverage.cmake

At some point during development, the required programs to compute C++ coverage and prepare reports were removed. 
This was not detected because cmake keeps a cache in the developer machine.
This PR re-introduces required infrastructure for c++ coverage. 
This issue was detected during Issues migration from the old organization.

EVMZERO: Fix issue in C++ coverage system

---

.gitmodules

The [emvc repo](https://github.com/0xsoniclabs/evmc) has been added to the new organization. Its `tosca-extensions` branch has also been rebased to the latest changes of the base branch.

Update evmc dependency

---

go/interpreter/lfvm/instructions.go
go/interpreter/lfvm/instructions_test.go

This PR adds the gas consumption for a warm/cold delegation designation address introduced with eip-7702 in the Prague revision.

LFVM: Add eip-7702 delegation designation

---

go/ct/common/bytes.go
go/ct/common/bytes_test.go
go/ct/driver/run.go
go/ct/st/serialization_test.go
go/ct/st/state_test.go

The `Bytes`' type string and json output lead to some confusion in the past. The `String` and `MarshalJSON` methods have been unified.
The input state has been printed twice in case of a failure.
Clarification which value is from the CT and which from the interpreter under test has been added.

CT: refactor json and string output

---

go/interpreter/lfvm/lfvm.go

This enables Prague features for execution and CT.

Enable lfvm prague features

---

go/ct/common/delegator_designator.go
go/ct/common/delegator_designator_test.go
go/ct/gen/accounts.go
go/ct/gen/accounts_test.go
go/ct/gen/state.go
go/ct/rlz/conditions.go
go/ct/rlz/conditions_test.go
go/ct/rlz/domains.go
go/ct/rlz/domains_test.go
go/ct/spc/specification.go

[EIP-7702](https://eips.ethereum.org/EIPS/eip-7702) introduces a small change on dynamic costs for all four call interpreter instructions. 
This PR is organized by commits, visiting one commit at the time is recommended for review. 
**The EIP change:**
- The delegation-designator is a 23 byte slice which consists of the `0xef, 0x01, 0x00` prefix and a target account address (the delegate account).
- The delegation-designator is to be stored in the code storage of the account pointed by the second parameter of a call instruction, instead of a valid opcodes slice. 
-  Any call operation, finding a delegation-designator in the code storage of the address being called, needs to charge EIP-2929 gas costs based in the warm/cold status of the delegation address. 
This PR adds CT support to …

Add CT support to check EIP-7702 semantics. 

---

cpp/vm/evmzero/interpreter.cc
cpp/vm/evmzero/interpreter_test.cc
go/interpreter/evmzero/evmzero.go

This PR adds the delegation designation billing to the `evmzero`. With these changes, the interpreter now fully supports the Prague revision.

evmzero: Add eip-7702 delegation designation cost

---

.github/workflows/rust.yaml
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs
rust/src/lib.rs
rust/src/types/code_analysis.rs
rust/src/types/code_reader.rs
rust/src/types/mod.rs
rust/src/types/observer.rs
rust/src/types/op_fn_data.rs
rust/src/types/opcode.rs

This PR removes the `fn-ptr-conversion-inline-dispatch` feature.
`fn-ptr-conversion-inline-dispatch` is slower than `fn-ptr-conversion-expanded-dispatch`, more complicated and requires unsafe code.
Additionally, `fn-ptr-conversion-expanded-dispatch` is renamed to `fn-ptr-conversion-dispatch` because it is now the only dispatch doing conversion during the code analysis. Because of that, the helper feature `needs-fn-ptr-conversoion` also be removed.

evmrs: remove feature fn-ptr-conversion-inline-dispatch

---

.github/workflows/rust.yaml
rust/Cargo.toml
rust/benchmarks/Cargo.toml
rust/src/interpreter.rs
rust/src/lib.rs
rust/src/types/code_reader.rs
rust/src/utils/mod.rs

This PR removes switch dispatch, makes jumptable dispatch the default and therefore also removes the feature `jumptable-dispatch`.
Because all dispatch technique now need the jumptable, the helper feature `needs-jumptable` is also removed.

evmrs: remove switch dispatch and make jumptable dispatch the default

---

rust/src/types/memory.rs

Currently, Memory:.get_word uses unsafe code to avoid the range check, because it is known that the slice is always 32 bytes long.
This PR rewrites get_word such that by default no unsafe code is used, but when feature unsafe-hints is enabled compiler hints are added to remove the range check again.

evmrs: put unsafe hint in Memory::get_word behind feature unsafe-hints

---

rust/fuzz/fuzz_targets/evmc_execute.rs

#63 failed because the call depth overflowed. This only happend because until now the call depth was not restricted to valid values. This PR changes that and makes sure that the input call depth is always in the range 0..=1024.

evmrs: set call depth input range for fuzzer to 0..=1024

---

rust/evmc-vm/src/container.rs
rust/evmc-vm/src/lib.rs
rust/evmc-vm/src/types.rs

This PR makes evmc-vm compatible with tosca by adding the steppable interface and code_hash field.
This is just a squashed version of:
- https://github.com/fantom-foundation/evmc/pull/3
- https://github.com/fantom-foundation/evmc/pull/4

evmrs(evmc-vm): add steppable evmc interface and add code_hash field to ExecutionMessage

---

rust/evmc-vm/src/container.rs
rust/evmc-vm/src/lib.rs

This PR fixes undefined behavior in evmc-vm.
In particular it avoids allocations of size 0 and uses `repr(C)` for the container types so that is ensured that the first field is at offset 0.
This PR contains parts of:
- https://github.com/Fantom-foundation/evmc/pull/5
- https://github.com/Fantom-foundation/evmc/pull/6

evmrs(evmc-vm): fix UB

---

.github/workflows/rust.yaml
rust/fuzz/Cargo.toml

Currently, fuzzing can fail because of overflows because the fuzz runner by default compiles the code with additional overflow checks. However, in some cases operations are expected to wrap around. This PR uses the default release profile instead, and also enables the performance feature of evmrs when fuzzing.

evmrs: fuzz with release profile and performance feature

---

rust/Cargo.toml
rust/benchmarks/src/lib.rs
rust/evmc-vm/src/container.rs
rust/evmc-vm/src/lib.rs
rust/src/evmc.rs
rust/src/ffi/evmc_vm.rs
rust/src/ffi/steppable_evmc_vm.rs
rust/src/interpreter.rs
rust/src/types/mock_execution_message.rs
rust/src/types/status_code.rs

This PR changes the type for the fields `input`, `code`, `output` and `last_call_return_data` from optional slices or optional boxed slices to slices or boxes slices.
Semantically, there is no difference between having no input or empty input (the same also holds for the other fields).
By making the fields non-optional, it is now sufficient to check if they are empty instead of checking if they are None or empty. This also removes branching overall.

evmrs: use empty containers instead of optional ones

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

The `isPrecompiledContract` function in the geth adapter is hard to read and error prone, this refactor uses geth's precompile definitions to check whether an address is a precompiled contract.

Geth adapter: Refactor isprecompiled function

---

go/ct/gen/code.go
go/ct/spc/specification.go

This PR fixes 2 findings, one of ineffective assigns and the other a misspelling typo, both from linters to be added by https://github.com/0xsoniclabs/tosca/pull/86.
ineffective assign analysis: 
the flagged assignment is `op := vm.INVALID` in `go/ct/gen/code.go:190`, at the beginning of a `for` loop.
if `nextFixedPosition < i` then the function exits, and does not return nor uses `op` 
if `i == nextFixedPosition` then the first thing it does is to assings a new value to `op`
if `i != nextFixedPosition` then a limit variable is calculated and after assigns `op = vm.OpCode(rnd.Int())` before using it.
given that the last 2 conditions are `if {} else {}` op will always be assigned before being used, rendering the initial assignment ineffectual.

Fix typo and ineffectual assignment

---

go/ct/gen/state.go
go/ct/gen/storage.go
go/ct/rlz/conditions.go
go/examples/example.go
go/examples/static_overhead.go
go/tosca/vm/opcodes.go

This PR fixes findings by `staticcheck` rule ST1020.
This rule enforces that the documentation, if any, of an exported method must begin with the name of the method.
This rule will be activated with https://github.com/0xsoniclabs/tosca/pull/86

Fix documentation of exported methods

---

go/ct/gen/block_context_test.go
go/ct/gen/range_solver.go
go/ct/rlz/conditions.go

This PR fixes findings by `staticcheck` rule `QF1001`.
This rule reports possible applications of [De Morgan's Law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws).
In particular, there is only one reported finding, in a test for of version number ordering, where a positive proposition is preferred.
This rule will be activated with https://github.com/0xsoniclabs/tosca/pull/86

Apply DeMorgan's law

---

go/interpreter/lfvm/instruction_logger.go

This PR fixes findings by `staticcheck` rule `QF1012`.
This rule reports when a call to a `Writer` contains a call to `fmt.Sprintf` and suggests its replacement by `fmt.Fprintf(writer, ...)`. 
This rule will be activated with https://github.com/0xsoniclabs/tosca/pull/86

Fix static check QF1012

---

go/interpreter/evmc/evmc_interpreter.go

The Go bindings of the [EVMC](https://github.com/ethereum/evmc) package [require](https://github.com/ethereum/evmc/blob/496ce0f81058378b72d0b592d1c49b935bce3302/bindings/go/evmc/host.go#L230)  [Error](https://github.com/ethereum/evmc/blob/496ce0f81058378b72d0b592d1c49b935bce3302/bindings/go/evmc/evmc.go#L82)s of a specific type to be reported upon calls. 
So far, this was only correctly reported in case of a revert. In other cases, an arbitrary error was reported, leading to a type-casting failure in the EVMC binding if such an error is emitted. This change is returning a generic `Failure` error in all other cases.

Fix reporting of errors to EVMC host context

---

.golangci.yml
Jenkinsfile
Makefile
go/ct/spc/staticcheck.conf
go/ct/staticcheck.conf

This PR introduces `golangci-lint` which is a go linters runner. Linters which are enabled includes:
- errcheck
- govet
- ineffassign
- misspell
- staticcheck
- unused
The linters currently used in Tosca are errcheck, govet, staticcheck. 
`Jenkinsfile` now calls to `make lint-go`
`make lint-go` now uses golangci.
This PR will remain a draft untill

Add golangci lint

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

This PR adds an end to end test for the gas refund handling in the geth adapter by simulating the refund logic of the stateDb.

Geth adapter: Gas refund end to end test

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

Return value, gas and error need to be handled by the adapter depending on the return values of the interpreter. A table test is used to check different combinations of return values against their expected values.

Geth adapter: unit test stressing interpreter return values

---

go/geth_adapter/adapter.go
go/geth_adapter/adapter_test.go

This PR removes panics and adds unit tests for the max call depth check and `...Log` functions.

Geth adapter: remove panics and add unit tests

---

go/interpreter/geth/geth.go
go/interpreter/geth/geth_test.go
go/processor/geth/processor.go
go/processor/geth/processor_test.go
go/tosca/processor.go

This PR adds Prague support to the processor types and geth reference implementation by adding `SetCodeAuthorizations` and refactoring the `MakeChainConfig` function.

Processor: Add prague support

---

go/processor/floria/precompiled.go
go/processor/floria/precompiled_test.go
go/processor/floria/run_context.go
go/processor/floria/run_context_test.go
go/processor/floria/state_contract.go
go/processor/floria/state_contract_test.go

This PR adds an overflow check to the gas calculation of precompiled contracts and makes sure they are also handled correctly in a delegate call by using the code address.

Floria: precompiled contracts

---

go/processor/floria/processor.go
go/processor/floria/processor_test.go

By moving all checks pre checks before the gas is bought, the snapshot and rollback can be eliminated. None of the checks has any impact on the state, once the gas is bought, a receipt is produced and the gas is charged also in failure cases. 
This PR should enable the restructuring of the `Run` function.

Floria: unify error handling of pre checks

---

go/integration_test/processor/processor_gas_test.go
go/processor/floria/processor.go
go/processor/geth/processor.go
go/processor/geth/processor_test.go
go/processor/opera/processor.go
go/processor/opera/processor_test.go

In case of an error, the receipt should be ignored and therefore also the gas used. The geth reference implementation and floria were checked against the ethereum tests and execution spec tests to ensure geth does not require a specific gas value in the case of an error.

Processor: Ignore gas used in case of error

---

go/processor/floria/processor.go
go/processor/floria/processor_test.go

This PR restructures the unit tests of the `processor.go` file, it consists of two parts:
- The first commit only reorders the unit tests and adds section diver comments.
- The second commit adds further unit tests.

Floria: restructure run unit tests 

---

go/processor/floria/run_context.go
go/processor/floria/run_context_test.go

This PR splits the implementation of CREATE and CREATE2 into multiple functions, improving readability and testability. Several unit tests are added covering the new functions.

Floria: refactor create implementation

---

go/processor/floria/run_context.go
go/processor/floria/run_context_test.go

This PR refactors the implementation of the different call types into the following structure:
- update `runContext` fields, see #128 
- create snapshot
- value transfer
- state contract
- precompiled contract
- interpreter execution
- result handling and rollback, to be refactored in a follow up PR

Floria: restructure call implementation

---

go/geth_adapter/state_db.go
go/geth_adapter/state_db_test.go

This PR fixes the creation and restoration of snapshots in the `geth_adaptor`'s StateDB as it is used by Tosca's geth reference processor implementation.
Before this fix, the implementation depended on the underlying system to produce distinct snapshot IDs for each call. However, this is not the case for some implementations, in particular the `Carmen` DB, which may reuse IDs.
With this fix, this problem got resolved.

Fix handling of snapshots of refund states in state DB adapter

---

rust/Cargo.toml
rust/src/types/op_fn_data.rs
rust/src/types/stack.rs

This PR sets the minimum supported Rust version (MSRV) in `Cargo.toml` to `1.86`.
This does not change the MSRV, it just configures it so that if an older version of Rust is used, once gets a more helpful error message.
This PR also fixes clippy lints that have been introduced in newer Rust versions (up to `1.89`).
Those lints do not break CI because Rust is already pinned to `1.86` in CI.

Configure MSRV and fix new clippy lints
